=== allencch/prayer-clock/res/prayers.dtd
<!ELEMENT prayers (prayer)>
<!ELEMENT prayer (time*,text)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST prayer title CDATA #REQUIRED>
<!ATTLIST prayer easter CDATA #IMPLIED>

=== allencch/prayer-clock/res/prayers.xml
<?xml version="1.0"?>
<!DOCTYPE prayers SYSTEM "prayers.dtd">
<prayers>
	<prayer title="Opening">
		<text>O God, come to my aid.
O Lord, make haste to help me.</text>
	</prayer>
	<prayer title="Angelus">
		<time>6:00:00</time>
		<time>12:00:00</time>
		<time>18:00:00</time>
		<text>V. The Angel of the Lord declared to Mary.
R. And she conceived of the Holy Spirit.

Hail Mary, full of grace, the Lord is with thee; blessed art thou among women and blessed is the fruit of thy womb, Jesus. Holy Mary, Mother of God, pray for us sinners, now and at the hour of our death. Amen.

V. Behold the handmaid of the Lord.
R. Be it done unto me according to Thy word.

[b]Hail Mary.[/b]

V. And the Word was made Flesh.
R. And dwelt among us.

[b]Hail Mary.[/b]

Pray for us, O Holy Mother of God, that we may be made worthy of the promises of Christ.

[i]Let us pray.[/i]
Pour forth, we beseech Thee, O Lord, Thy grace into our hearts; that we, to whom the incarnation of Christ, Thy Son, was made known by the message of an angel, may by His Passion and Cross be brought to the glory of His Resurrection, through the same Christ Our Lord.

Amen.</text>
	</prayer>
	<prayer title="3 O'Clock Prayer">
		<time>15:00:00</time>
		<text>You expired, Jesus, but the source of life gushed forth for souls and the ocean of mercy opened up for the whole world. O Fountain of Life, unfathomable Divine Mercy, envelop the whole world and empty Yourself out upon us.

O Blood and Water, which gushed forth from the Heart of Jesus as a fountain of mercy for us, I trust in You. (3 times)</text>
	</prayer>

	<prayer title="Regina Caeli">
		<time>6:00:00</time>
		<time>12:00:00</time>
		<time>18:00:00</time>
		<text>Queen of Heaven, rejoice, Alleluia.
For He whom you did merit to bear, Alleluia.

Has risen, as he said, Alleluia.
Pray for us to God, Alleluia.

Rejoice and be glad, O Virgin Mary, Alleluia.
For the Lord has truly risen, Alleluia.

[i]Let us pray.[/i]
O God, who gave joy to the world through the resurrection of Thy Son, our Lord Jesus Christ, grant we beseech Thee, that through the intercession of the Virgin Mary, His Mother, we may obtain the joys of everlasting life. Through the same Christ our Lord.

Amen.</text>
	</prayer>
	<prayer title="Divine Mercy Novena 1st Day" easter="-2">
		<text>"[b]Today bring to Me all mankind, especially all sinners[/b],

and immerse them in the ocean of My mercy. In this way you will console Me in the bitter grief into which the loss of souls plunges Me."

Most Merciful Jesus, whose very nature it is to have compassion on us and to forgive us, do not look upon our sins but upon our trust which we place in Your infinite goodness. Receive us all into the abode of Your Most Compassionate Heart, and never let us escape from It. We beg this of You by Your love which unites You to the Father and the Holy Spirit.

Eternal Father, turn Your merciful gaze upon all mankind and especially upon poor sinners, all enfolded in the Most Compassionate Heart of Jesus. For the sake of His sorrowful Passion show us Your mercy, that we may praise the omnipotence of Your mercy for ever and ever. Amen.</text>
	</prayer>
	<prayer title="Divine Mercy Novena 2nd Day" easter="-1">
		<text>"[b]Today bring to Me the Souls of Priests and Religious[/b],

and immerse them in My unfathomable mercy. It was they who gave me strength to endure My bitter Passion. Through them as through channels My mercy flows out upon mankind."

Most Merciful Jesus, from whom comes all that is good, increase Your grace in men and women consecrated to Your service,* that they may perform worthy works of mercy; and that all who see them may glorify the Father of Mercy who is in heaven.

Eternal Father, turn Your merciful gaze upon the company of chosen ones in Your vineyard -- upon the souls of priests and religious; and endow them with the strength of Your blessing. For the love of the Heart of Your Son in which they are enfolded, impart to them Your power and light, that they may be able to guide others in the way of salvation and with one voice sing praise to Your boundless mercy for ages without end. Amen.

    * In the original text, Saint Faustina uses the pronoun "us" since she was offering this prayer as a consecrated religious sister. The wording adapted here is intended to make the prayer suitable for universal use.</text>
    </prayer>
    <prayer title="Divine Mercy Novena 3rd Day" easter="0">
    	<text>"[b]Today bring to Me all Devout and Faithful Souls[/b],

and immerse them in the ocean of My mercy. These souls brought me consolation on the Way of the Cross. They were a drop of consolation in the midst of an ocean of bitterness."

Most Merciful Jesus, from the treasury of Your mercy, You impart Your graces in great abundance to each and all. Receive us into the abode of Your Most Compassionate Heart and never let us escape from It. We beg this grace of You by that most wondrous love for the heavenly Father with which Your Heart burns so fiercely.

Eternal Father, turn Your merciful gaze upon faithful souls, as upon the inheritance of Your Son. For the sake of His sorrowful Passion, grant them Your blessing and surround them with Your constant protection. Thus may they never fail in love or lose the treasure of the holy faith, but rather, with all the hosts of Angels and Saints, may they glorify Your boundless mercy for endless ages. Amen.</text>
	</prayer>
	<prayer title="Divine Mercy Novena 4th Day" easter="1">
		<text>"[b]Today bring to Me those who do not believe in God and those who do not know Me[/b],

I was thinking also of them during My bitter Passion, and their future zeal comforted My Heart. Immerse them in the ocean of My mercy."

Most compassionate Jesus, You are the Light of the whole world. Receive into the abode of Your Most Compassionate Heart the souls of those who do not believe in God and of those who as yet do not know You. Let the rays of Your grace enlighten them that they, too, together with us, may extol Your wonderful mercy; and do not let them escape from the abode which is Your Most Compassionate Heart.

Eternal Father, turn Your merciful gaze upon the souls of those who do not believe in You, and of those who as yet do not know You, but who are enclosed in the Most Compassionate Heart of Jesus. Draw them to the light of the Gospel. These souls do not know what great happiness it is to love You. Grant that they, too, may extol the generosity of Your mercy for endless ages. Amen.

    *Our Lord's original words here were "the pagans." Since the pontificate of Pope John XXIII, the Church has seen fit to replace this term with clearer and more appropriate terminology.</text>
    </prayer>
    <prayer title="Divine Mercy Novena 5th Day" easter="2">
    	<text>"[b]Today bring to Me the Souls of those who have separated themselves from My Church*[/b],

and immerse them in the ocean of My mercy. During My bitter Passion they tore at My Body and Heart, that is, My Church. As they return to unity with the Church My wounds heal and in this way they alleviate My Passion."

Most Merciful Jesus, Goodness Itself, You do not refuse light to those who seek it of You. Receive into the abode of Your Most Compassionate Heart the souls of those who have separated themselves from Your Church. Draw them by Your light into the unity of the Church, and do not let them escape from the abode of Your Most Compassionate Heart; but bring it about that they, too, come to glorify the generosity of Your mercy.

Eternal Father, turn Your merciful gaze upon the souls of those who have separated themselves from Your Son's Church, who have squandered Your blessings and misused Your graces by obstinately persisting in their errors. Do not look upon their errors, but upon the love of Your own Son and upon His bitter Passion, which He underwent for their sake, since they, too, are enclosed in His Most Compassionate Heart. Bring it about that they also may glorify Your great mercy for endless ages. Amen.

    *Our Lord's original words here were "heretics and schismatics," since He spoke to Saint Faustina within the context of her times. As of the Second Vatican Council, Church authorities have seen fit not to use those designations in accordance with the explanation given in the Council's Decree on Ecumenism (n.3). Every pope since the Council has reaffirmed that usage. Saint Faustina herself, her heart always in harmony with the mind of the Church, most certainly would have agreed. When at one time, because of the decisions of her superiors and father confessor, she was not able to execute Our Lord's inspirations and orders, she declared: "I will follow Your will insofar as You will permit me to do so through Your representative. O my Jesus " I give priority to the voice of the Church over the voice with which You speak to me" (497). The Lord confirmed her action and praised her for it.</text>
    </prayer>
    <prayer title="Divine Mercy Novena 6th Day" easter="3">
    	<text>"[b]Today bring to Me the Meek and Humble Souls and the Souls of Little Children[/b],

and immerse them in My mercy. These souls most closely resemble My Heart. They strengthened Me during My bitter agony. I saw them as earthly Angels, who will keep vigil at My altars. I pour out upon them whole torrents of grace. I favor humble souls with My confidence."
